### ISSUE TITLE
Cannot build Pictish: could not resolve artifacts

### ISSUE THREAD

**Issue by chocorho** [DeflatedPickle/Pictish#1]
**Describe the bug**
When using `./gradlew build`, I encounter the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileCommonMainKotlinMetadata'.
> Could not resolve all artifacts for configuration ':allSourceSetsCompileDependenciesMetadata'.
   > Could not find com.github.spoptchev:kotlin-preconditions:6.1.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/spoptchev/kotlin-preconditions/6.1.1/kotlin-preconditions-6.1.1.pom
       - file:/home/chozorho/.m2/repository/com/github/spoptchev/kotlin-preconditions/6.1.1/kotlin-preconditions-6.1.1.pom
       - https://jitpack.io/com/github/spoptchev/kotlin-preconditions/6.1.1/kotlin-preconditions-6.1.1.pom
     Required by:
         project :
   > Could not find me.sargunvohra.lib:ktunits:1.1.2.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/me/sargunvohra/lib/ktunits/1.1.2/ktunits-1.1.2.pom
       - file:/home/chozorho/.m2/repository/me/sargunvohra/lib/ktunits/1.1.2/ktunits-1.1.2.pom
       - https://jitpack.io/me/sargunvohra/lib/ktunits/1.1.2/ktunits-1.1.2.pom
     Required by:
         project :
```

One can resolve the `kotlin-reconditions:6.1.1` by replacing the version number with `6.1.0`; this version specifies the closest artifact available on the [jitpack site](https://jitpack.io/com/github/spoptchev/kotlin-preconditions/). But there is no similar version for ktunits -- is there? Their [GitHub repository](https://github.com/sargunv/ktunits) gives unclear or incomplete information about the most recent version number. Have you found a way around this?

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to project root dir
2. Invoke `./gradlew build`

**Desktop:**
 - OS: Devuan GNU/Linux Chimaera
 - Version: Linux 5.10.0-8-amd64

**Comment by DeflatedPickle** [comment]
I haven't actually started working on this yet, sorry. It's just a template
